### ISSUE TITLE
请问能共享一下操作系统切换输入法的代码吗?

### ISSUE THREAD

**Issue by hadix-lin** [3xp10it/AutoIM#1]

**Comment by 3xp10it** [comment]
使用squirrel的话直接用default.custom.yaml配置就可以了,不过后来发现用久了不太好用,后来改成了用fcitx-vim-osx,fcitx-vim-osx效果很好:
https://github.com/CodeFalling/fcitx-vim-osx
https://github.com/CodeFalling/fcitx-remote-for-osx

**Comment by hadix-lin** [comment]
可惜,这两个输入法都不是我想用的.
